# Generated by Django 5.0.6 on 2024-06-05 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AWARDS_CERTIFICATIONS',
            new_name='Award_Certification',
        ),
        migrations.RenameModel(
            old_name='INTERESTS',
            new_name='Interest',
        ),
        migrations.RenameModel(
            old_name='SKILLS',
            new_name='Skill',
        ),
    ]
