# Generated by Django 5.0.6 on 2024-06-08 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_rename_awards_certifications_award_certification_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Award_Certification',
            new_name='AwardCertification',
        ),
    ]
