# Generated by Django 5.0.6 on 2024-06-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='adress',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
