# Generated by Django 5.0.6 on 2024-06-05 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_phone_number_alter_account_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='bio',
            new_name='biography',
        ),
    ]
